# Generated by Django 4.1.5 on 2023-01-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='number_of_bids',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('motors', 'Motors'), ('electronics', 'Electronics'), ('art', 'Collectibles & Art'), ('clothing', 'Clothing & Accessories'), ('business', 'Business & Industrial'), ('home', 'Home & Garden'), ('sport', 'Sporting goods'), ('jewel', 'Jewelry & Watches'), ('other', 'Others')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
