# Generated by Django 4.1.5 on 2023-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_issold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='issold',
            new_name='isclosed',
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.auction'),
        ),
    ]
